apiVersion: v1
kind: ReplicationController
metadata: 
  name: sh-account
  labels:
    name: sh-account
spec: 
  replicas: 1
  selector: 
    name: sh-account
  template: 
    metadata:
      labels: 
        name: sh-account
    spec: 
      containers:
      - name: account
        image: 192.168.0.81:5000/sh-account:v22
        command:
        - start_nginx 
        ports:
        - containerPort: 80 
